# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d92c14d0946cb3482f48c2bee633b62f77f53c19dd0bd73a679a417bb40f20cad33cd6d09a8d7f8a12e1810e66c16b06aeac9d16e9455f8bc6dc411fafafca91

test:
  secret_key_base: 6fee68687741baffe5b8dcca90fc190dc158e3bb75eeddde42576a8be34b60aba05d1e3914938f356bd92bcd524a8d9af033c7978947d81846a29d418c5cce2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
