# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adca1edcc5316e8e94d7d7caa0f51c016869e2d9aee6170d1fb43b73310f74403c06a6d4ecb556baa438ba740d4b8b795eb89c89885d15724f2f269db0b76ecb

test:
  secret_key_base: 7142bd9cf5ab59ba006bc705fb4ebe6dc2e4d6146a0203d8dc2b9f45c10caca0bacd55477e18d01b4917498cca9942020d86e025a42b1c79049542aae4fe903f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
