# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16a7c38fd1006d172759a7285b53aa653739b8e0b934c58158bfdd19a252d7377d5163238754d33bcd51c75c6804fd04a382cd1f8a1913bb03d199ed6d0480c9

test:
  secret_key_base: 91bb4dd454fcd65949611d79f36a8b3134dfcab7e9cb5ab5f5002c43e47903e6e94c77618e8160f7c933b04f4eb793b17488d20332492be3314e34fc260e32ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
